# Generated by Django 4.1.3 on 2022-12-08 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TestModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TypeFichier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FormatCsv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_line_separator', models.CharField(max_length=5)),
                ('csv_field_separator', models.CharField(max_length=1)),
                ('csv_encoding', models.CharField(max_length=15)),
                ('decimal_separator', models.CharField(max_length=1)),
                ('date_format', models.CharField(max_length=10)),
                ('type_fich', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='afpi_import_csv.typefichier')),
            ],
        ),
        migrations.CreateModel(
            name='CorrespondanceColonnes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colonne_initiale', models.CharField(max_length=50)),
                ('champ_cible', models.CharField(max_length=50)),
                ('flag_doublon', models.BooleanField()),
                ('flag_foreignkey', models.BooleanField()),
                ('classe_liee', models.CharField(max_length=50)),
                ('champ_identification_classe', models.CharField(max_length=50)),
                ('type_fich', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afpi_import_csv.typefichier')),
            ],
        ),
    ]
