# Generated by Django 4.1.3 on 2022-12-10 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afpi_import_csv', '0002_alter_correspondancecolonnes_champ_identification_classe_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel1',
        ),
        migrations.DeleteModel(
            name='TestModel2',
        ),
    ]
