# Generated by Django 4.1.3 on 2022-12-10 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afpi_import_csv', '0004_testmodel1_testmodel2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel2',
            name='agence',
        ),
        migrations.DeleteModel(
            name='TestModel1',
        ),
        migrations.DeleteModel(
            name='TestModel2',
        ),
    ]
