# Generated by Django 4.1.3 on 2022-12-12 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=20)),
                ('no_compta', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('banque', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ecriture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_operation', models.DateField()),
                ('date_valeur', models.DateField()),
                ('debit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('libelle', models.CharField(max_length=100)),
                ('hors_compta', models.BooleanField(default=False)),
                ('compte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.compte')),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('emise', 'emise'), ('recue', 'recue')], max_length=10)),
                ('emetteur', models.CharField(max_length=50)),
                ('date_emission', models.DateField()),
                ('date_recouvrement', models.DateField()),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fichier', models.FileField(upload_to='')),
                ('commercial', models.CharField(max_length=20)),
                ('apporteur', models.CharField(max_length=20)),
                ('retrocession_commercial', models.DecimalField(decimal_places=2, max_digits=8)),
                ('retrocession_apporteur', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ElementComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.categoriecomptable')),
                ('ecriture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comptabilite.ecriture')),
                ('facture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comptabilite.facture')),
            ],
        ),
    ]
