# Generated by Django 4.1.3 on 2022-12-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementcomptable',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='elementcomptable',
            name='montant',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
