# Generated by Django 4.1.3 on 2023-01-26 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_elementcomptable_date_elementcomptable_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='date_recouvrement',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montant',
        ),
        migrations.AddField(
            model_name='facture',
            name='date_retro_apporteur',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_retro_commercial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='future_facture',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elementcomptable',
            name='facture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comptabilite.facture'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='apporteur',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='commercial',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_emission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='facture',
            name='retrocession_apporteur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='retrocession_commercial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.CreateModel(
            name='Echeance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_recouvrement', models.DateField()),
                ('facture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comptabilite.facture')),
            ],
        ),
    ]
