# Generated by Django 4.1.3 on 2023-02-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_alter_ecriture_credit_alter_ecriture_debit'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='plusieurs_ecritures',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
