# Generated by Django 4.1.3 on 2023-02-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_facture_plusieurs_ecritures'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriecomptable',
            name='intitule',
            field=models.CharField(max_length=40),
        ),
    ]
