# Generated by Django 4.1.3 on 2023-01-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_remove_facture_date_recouvrement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facture',
            name='apporteur',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='commercial',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='date_retro_apporteur',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='date_retro_commercial',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='retrocession_apporteur',
        ),
        migrations.RemoveField(
            model_name='facture',
            name='retrocession_commercial',
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
