# Generated by Django 4.1.3 on 2023-02-28 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0005_alter_elementcomptable_categorie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementcomptable',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie_elem', to='comptabilite.categoriecomptable'),
        ),
    ]
